version: '3'

services:
    node1:
      image: mongo
      ports:
        - 30001:27071
      volumes:
        - $HOME/mongoclusterdata/node1:/data/db
      networks:
        - mongocluster
      command: mongod --replSet comments
    node2:
      image: mongo
      ports:
        - 30002:27071
      volumes:
        - $HOME/mongoclusterdata/node2:/data/db
      networks:
        - mongocluster
      command: mongod --replSet comments
      depends_on:
        - node1
    node3:
      image: mongo
      ports:
        - 30003:27071
      volumes:
        - $HOME/mongoclusterdata/node3:/data/db
      networks:
        - mongocluster
      command: mongod --replSet comments
      depends_on:
        - node2

networks:
  mongocluster:
    driver: bridge


